### ISSUE TITLE
Support enrollMfa and requestMfa using API

### ISSUE THREAD

**Issue by g0josh** [auth0/auth0-flutter#168]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Please add support for enrolling and requesting MFA challenges using API. 

### Describe the ideal solution

- enrollMfa for doing what `https://YOUR_DOMAIN/mfa/associate` does, as of now I'd have to use the REST endpoint
- requestMfa for issuing a challenge if I have my authenticator enrolled. Something like what [Auth0.swift does](https://auth0.github.io/Auth0.swift/Protocols/Authentication.html#/s:5Auth014AuthenticationP20multifactorChallenge8mfaToken5types15authenticatorIdAA7RequestVyAA0D0VAA0B5ErrorVGSS_SaySSGSgSSSgtF:~:text=multifactorChallenge(mfaToken%3Atypes%3AauthenticatorId%3A))
- loginMfa for logging in with the authenticator code received, [Auth0.swift example](https://auth0.github.io/Auth0.swift/Protocols/Authentication.html#/s:5Auth014AuthenticationP20multifactorChallenge8mfaToken5types15authenticatorIdAA7RequestVyAA0D0VAA0B5ErrorVGSS_SaySSGSgSSSgtF:~:text=login(withOOBCode%3AmfaToken%3AbindingCode%3A))

### Alternatives and current workarounds

Enrolling can be done using the REST api and requesting for a challenge can be done using the REST api as [mentioned here](https://auth0.com/docs/secure/multi-factor-authentication/authenticate-using-ropg-flow-with-mfa/enroll-and-challenge-otp-authenticators). But [completing authentication using the received MFA token](https://auth0.com/docs/secure/multi-factor-authentication/authenticate-using-ropg-flow-with-mfa/enroll-and-challenge-otp-authenticators#complete-authentication-using-received-code) is where the problem is. The document says to do 
```
curl --request POST \
  --url 'https://YOUR_DOMAIN/oauth/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=http://auth0.com/oauth/grant-type/mfa-otp \
  --data 'client_id=YOUR_CLIENT_ID' \
  --data client_secret=YOUR_CLIENT_SECRET \
  --data mfa_token=MFA_TOKEN \
  --data otp=USER_OTP_CODE
```
But I would not have the `YOUR_CLIENT_SECRET`. Is it safe to avoid this? I see its not used in [auth0.swift implementation](https://github.com/auth0/Auth0.swift/blob/94583919777f0abfb1c2caa5ff2a420d54ec770d/Auth0/Auth0Authentication.swift#L83)

**Comment by Widcket** [comment]
Hi @g0josh, thanks for raising this.

Enrolling would be out of the scope of this SDK. We have native libraries for this, though:
- [Guardian.Android](https://github.com/auth0/Guardian.Android/)
- [Guardian.swift](https://github.com/auth0/Guardian.swift/)

Regarding requesting the MFA challenge and then logging in with the authenticator code, we have no plans in the near term but I'll leave this issue open for future planning and reference.

> But I would not have the YOUR_CLIENT_SECRET. Is there any other way to doing this?

You don't need to include the client secret in the request if it's made from a native app (such as a Flutter app), because native apps are public clients and this means they're not able to hold credentials (such as the client secret) securely. The client secret can only be included in requests issued from confidential client, like a server-side app. See https://auth0.com/docs/get-started/applications/confidential-and-public-applications to learn more.

**Comment by wferem1** [comment]
Hi, we're also interested in this feature. 
I'm willing to create this myself, do you accept PR's for this feature?

**Comment by cbhernan** [comment]
With the support for Flutter Web and the recent change to the setting "Allow unchallenged MFA API access", is this now in scope for the Flutter SDK?
