### ISSUE TITLE
Could not resolve com.auth0.android:auth0:2.+

### ISSUE THREAD

**Issue by aymaalo** [auth0/auth0-flutter#181]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I have this new error I hadn't the last time I worked on my project (2 days ago).

It appears when I try to build my flutter app on my android device. I haven't changed anything to the code.

![image](https://user-images.githubusercontent.com/37023953/198897079-b6e5dc01-3183-4e8c-a0fb-1e55b372887d.png)

Please help !

### Reproduction

Build the app on an android device

### auth0_flutter version

1.0.1

### Flutter version

Stable 3.3.3

### Platform

Android

### Platform version(s)

Android SDK version 33.0.0

**Comment by bartcone-fulfilld** [comment]
@aymaalo There's currently a jcenter outage: https://status.gradle.com/incidents/9740r6bzx438

The current workaround I'm using is to specify dependency versions on the `auth0` and `jwtdecode` dependencies. These are found in the `auth0_flutter/android/build.gradle` file.

https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/android/build.gradle#L67
https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/android/build.gradle#L69

The latest look to be the following:
```
implementation 'com.auth0.android:auth0:2.8.0'
implementation 'com.auth0.android:jwtdecode:2.0.1'
```

You can find all version here: https://search.maven.org/search?q=com.auth0.android

You can edit these by finding the cached auth0 package under your flutter install path. e.g. mine is located here: `Users/<uname>/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/auth0_flutter-1.0.1/android/build.gradle`.

I'm guessing since they're dynamic right now, it's hitting all repositories even though the repositories section says:
```    
repositories {
        google()
        mavenCentral()
}
```

**Comment by Widcket** [comment]
Hi all,

The JCenter outage seems to be resolved:

<img width="662" alt="Screen Shot 2022-10-31 at 10 45 26" src="https://user-images.githubusercontent.com/5055789/199025761-adc99423-3589-42c5-b2bb-b43bba55917a.png">

I was able to build the example app:

<img width="1050" alt="Screen Shot 2022-10-31 at 10 59 30" src="https://user-images.githubusercontent.com/5055789/199025876-e2769238-6046-4b83-a73e-4a45328bfca7.png">
