### ISSUE TITLE
Enable claim validation by calling AuthenticationRequest#validateClaims() Issue

### ISSUE THREAD

**Issue by philip6560** [auth0/auth0-flutter#191]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I get this message `E/BaseAuthenticationRequest(24058): The request is made without validating claims. Enable claim validation by calling AuthenticationRequest#validateClaims()`. 

when I use the `auth0.api.login` method from the sdk on Android. Although the request goes through, however I am concerned as I don't know what this means.

I have been able to trace this to this file on the android-sdk `auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt` to a comment on line `67` about the method on line `79`.

### Reproduction

1. Make a call to `auth0.api.login()` with required parameters.
2. immediately after request is initiated check console for this `E/BaseAuthenticationRequest(24058): The request is made without validating claims. Enable claim validation by calling AuthenticationRequest#validateClaims()`.

### auth0_flutter version

auth0_flutter: ^1.0.2

### Flutter version

Flutter version 3.3.10 on channel stable 

### Platform

Android

### Platform version(s)

Android 13 (API 33)

**Comment by Widcket** [comment]
Hi @philip6560, thanks for raising this.

auth0_flutter wraps the [Auth0.Android](https://github.com/auth0/Auth0.Android) and [Auth0.swift](https://github.com/auth0/Auth0.swift) native SDKs. Since [v2.8.0](https://github.com/auth0/Auth0.Android/releases/tag/2.8.0), Auth0.Android supports [validating the claims](https://github.com/auth0/auth0.android/blob/main/EXAMPLES.md#token-validation) of ID tokens obtained through the Authentication API client. It is an opt-in feature, which is not enabled in auth0_flutter because it's not supported in Auth0.swift yet.

You can implement the logic for validating the ID token claims yourself, and disregard the `The request is made without validating claims. Enable claim validation by calling AuthenticationRequest#validateClaims()` message: https://auth0.com/docs/secure/tokens/id-tokens/validate-id-tokens

**Comment by philip6560** [comment]
@Widcket Thanks a lot, I'd check it out.
