### ISSUE TITLE
Issue with refreshing the token using credentials manager

### ISSUE THREAD

**Issue by Miloye1** [auth0/auth0-flutter#234]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello, I’m having trouble with the credentials manager. In the documentation it clearly states that the `credentials()` method “Retrieves the credentials from the storage and refreshes them if they have already expired.” [(docs),](https://pub.dev/documentation/auth0_flutter/latest/auth0_flutter/DefaultCredentialsManager/credentials.html) but I can’t seem to get it working. 

### Reproduction

I’m receiving the refresh_token after authenticating and I have set token duration to 30s. Also, I have set up the token rotation. But when I invoke the `credentials()` I get the same tokens back.

So, am I misunderstanding the credentials() method? Is it supposed to renew the tokens using the refresh_token or not?

My code:
```
import 'package:flutter/material.dart';
import 'package:auth0_flutter/auth0_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class AuthProvider extends ChangeNotifier {
  bool _isLoggedIn = false;

  final Auth0 auth0 = Auth0(dotenv.env["DOMAIN"]!, dotenv.env["CLIENT_ID"]!);

  bool get isLoggedIn {
    return _isLoggedIn;
  }

  Future<void> login() async {
    await auth0.webAuthentication(scheme: dotenv.env["AUTH0_SCHEME"]!).login();
    _isLoggedIn = true;
    notifyListeners();
  }

  Future<void> logout() async {
    await auth0.webAuthentication(scheme: dotenv.env["AUTH0_SCHEME"]!).logout();
    _isLoggedIn = false;
    notifyListeners();
  }

  Future<bool> isUserLoggedIn() async {
    final loggedIn = await auth0.credentialsManager.hasValidCredentials();
    if (loggedIn) {
      final credentials = await auth0.credentialsManager.credentials();
      print(credentials.expiresAt);
      print(credentials.idToken);
      print(credentials.accessToken);
      print(credentials.refreshToken);
    }
    if (loggedIn) {
      _isLoggedIn = true;

      return true;
    }

    return false;
  }

  Future<Credentials> getUserCredentials() async {
    return await auth0.credentialsManager.credentials();
  }
}
```

### auth0_flutter version

^1.1.0

### Flutter version

3.7.9

### Platform

Android

### Platform version(s)

13

**Comment by Widcket** [comment]
Hi @Miloye1, thanks for raising this.

Are you setting up the access token expiration (in your Auth0 API settings page) or the ID token expiration (in your Auth0 Application settings page)? The Credentials Manager only checks for the expiration of the access token.

Also please make sure to set the expiration before logging in, because the access token expiration comes with the credentials. It doesn't get checked/updated after that.

**Comment by Miloye1** [comment]
Hi @Widcket thanks for the response.

I wasn't setting the expiration time in the API settings, only on the application settings, and now the token is refreshed successfully.

But I still don't fully get how the APIs work so I guess I'll have to dig into the docs some more. We have a custom API for our backend, and when I set the expiration time there, and use it's identifier as audience, I don't get the refresh token in the response. But when I use the system Auth0 Management API instead it works. Is there an additional setting that should be configured?

Thanks in advance

**Comment by Widcket** [comment]
Make sure it's enabled in the API settings:

<img width="976" alt="Screenshot 2023-04-06 at 2 22 14 PM" src="https://user-images.githubusercontent.com/5055789/230451430-46fd0a3b-0fac-48bb-ba67-f50118571149.png">

**Comment by nhannguyenandpad** [comment]
Hi @Miloye1, does this actually fix your issue? Since I also can not refresh the token even after enabling Allow Offline Access.

**Comment by sarbogast** [comment]
I have the same issue: for testing, I set both the access token lifetime in the API and the id token lifetime in the application to 20 seconds. When I log in, I receive an id token that expires 20 seconds after it was issued, so perfect. But the expiresAt property on the credentials is 22 hours after the token was issued, and I don't know what setting determines that. The end result is that I get an expired id token, but the SDK does not refresh it like it should since based on expiresAt, it's not expired or even close to being expired. And I also decoded the JWT for the access token and there is not even an expiration date (exp) in this one, only in the id token.
