### ISSUE TITLE
Sign out looks like Sign in.

### ISSUE THREAD

**Issue by modulovalue** [auth0/auth0-flutter#437]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello auth0 team,

when trying to logout, the sign-in dialog appears. Is this a known issue or could something be misconfigured on my end?

This happens after initiating `....webAuthentication().logout(useHTTPS: true)` on iOS and macOS:

![IMG_4600FEBF2B5C-1](https://github.com/auth0/auth0-flutter/assets/24444584/b7f9b60e-6bd3-408a-87b0-71a2c4283edc)

### Reproduction

Call `....webAuthentication().logout(useHTTPS: true)`.

### auth0_flutter version

auth0_flutter: ^1.6.0

### Flutter version

Flutter 3.16.7 • channel stable • https://github.com/flutter/flutter.git Framework • revision ef1af02aea (3 months ago) • 2024-01-11 15:19:26 -0600 Engine • revision 4a585b7929 Tools • Dart 3.2.4 • DevTools 2.28.5

### Platform

iOS

**Comment by desusai7** [comment]
Hi @modulovalue, 

Yes, this is a known issue and unfortunately, this cannot be fixed due to the limitations of `ASWebAuthenticationSession`.

More about this can be found in the FAQ's [here](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md).  You may refer to the FAQ [#3](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md#3-how-can-i-disable-the-ios-logout-alert-box), [#4](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md#4-how-can-i-change-the-message-in-the-ios-alert-box) & [#5](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md#5-how-can-i-programmatically-close-the-ios-alert-box)

**Comment by modulovalue** [comment]
Thank you, @desusai7.
